spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bodybuddy
    username: root
    password: 4987
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: Asia/Seoul